[workspace]
members = [
    "emulator",
    "instruction-set",
    "programming-language/assistance", 
    "programming-language/compiler", 
    "programming-language/parser",
    "software/host",
    "software/graphical-interface"
]