[package]
name = "instruction-set"
version = "0.1.0"
edition = "2021"

[dependencies]

[lib]
name = "libfajr_instruction_set"
path = "lib/lib.rs"

[[bin]]
name = "fajr_instruction_set"
path = "bin/bin.rs"